"""General Agent behavior configuration."""

MAX_RELEVANT_SKILLS = 3
MAX_RELEVANT_MEMORIES = 5
MAX_SIMILAR_TASKS = 2
MAX_CONTEXT_CHARS = 12_000
SKILL_STABLE_SUCCESS_COUNT = 3
REPEAT_TASK_SUGGESTION_COUNT = 3
TOOL_TIMEOUT_SECONDS = 30
GENERATED_CODE_TIMEOUT_SECONDS = 20
MAX_RETRIES = 3

